package:
  name: undetected_playwright
  version: "{{ environ.get('GIT_DESCRIBE_TAG') | replace('v', '') }}"

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true # [py<37]
  binary_relocation: False
  missing_dso_whitelist: "*"
  entry_points:
    - undetected_playwright = undetected_playwright.__main__:main

requirements:
  host:
    - python
    - wheel
    - pip
    - curl
    - setuptools_scm
  run:
    - python
    - greenlet ==3.0.1
    - pyee ==11.0.1
    - typing_extensions # [py<39]
test:
  requires:
    - pip
  imports:
    - undetected_playwright
    - undetected_playwright.sync_api
    - undetected_playwright.async_api
  commands:
    - undetected_playwright --help

about:
  home: https://github.com/microsoft/playwright-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python version of the Playwright testing and automation library.
  description: |
    Playwright is a Python library to automate Chromium,
    Firefox and WebKit browsers with a single API. Playwright
    delivers automation that is ever-green, capable, reliable
    and fast.
  doc_url: https://playwright.dev/python/docs/intro/
  dev_url: https://github.com/microsoft/playwright-python
